default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  username: root
  password: admin

development:
  <<: *default
  database: contact_us_widget_dev

production:
  <<: *default
  database: contact_us_widget_prod

test:
  <<: *default
  database: contact_us_widget_test